blank_issues_enabled: false # must use template
contact_links:
  - name: tabmerger@googlegroups.com
    url: https://groups.google.com/g/tabmerger
    about: A community where you can ask questions, suggest features, and indicate potential issues with TabMerger
