name: CI

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["master"]

jobs:
  spell:
    runs-on: windows-2022

    strategy:
      matrix:
        node: [12, 14, 16]

    steps:
      - uses: actions/checkout@v2

      - name: Cache Modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: latest

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install Dependencies
        run: pnpm i --only=dev

      - name: Check Spelling
        run: pnpm spell:check

  format:
    runs-on: windows-2022
    needs: spell

    strategy:
      matrix:
        node: [12, 14, 16]

    steps:
      - uses: actions/checkout@v2

      - name: Cache Modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: latest

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install Dependencies
        run: pnpm i --only=dev

      - name: Format Write
        id: format
        run: |
          pnpm format:write
          echo "::set-output name=NUM_CHANGED::$(git add . && git status src | grep 'modified:' | wc -l)"

      - name: Format Success
        if: ${{ steps.format.outputs.NUM_CHANGED == 0 }}
        run: echo "All matched files use Prettier code style!"

      - name: Format Error
        if: ${{ steps.format.outputs.NUM_CHANGED > 0 }}
        run: |
          pnpm format:check
          echo "::error::Found formatting issues in ${{ steps.format.outputs.NUM_CHANGED }} of the above file(s). Forgot to run Prettier locally?"
          exit 1

  lint:
    runs-on: windows-2022
    needs: format

    strategy:
      matrix:
        node: [12, 14, 16]

    steps:
      - uses: actions/checkout@v2

      - name: Cache Modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: latest

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install Dependencies
        run: pnpm i

      - name: Lint Code
        run: pnpm lint:code

      - name: Lint Style
        run: pnpm lint:style
