name: Compressed Size Check

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: preactjs/compressed-size-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          pattern: "**/build/**/*.js"
          exclude: "{**/*.map,**/node_modules/**}"
