name: Spell Check | Lint | Format

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["master"]

jobs:
  spell:
    runs-on: windows-2022

    strategy:
      matrix:
        node: [12, 14, 16]

    steps:
      - uses: actions/checkout@v2

      - name: Cache Node Modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install Dependencies
        run: npm i

      - name: Check Spelling
        run: npm run spell:check

  format:
    runs-on: windows-2022
    needs: spell

    strategy:
      matrix:
        node: [12, 14, 16]

    steps:
      - uses: actions/checkout@v2

      - name: Cache Node Modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install Dependencies
        run: npm i

      - name: Format Write
        id: format
        run: |
          npm run format:write
          echo "::set-output name=NUM_CHANGED::$(git status | grep 'modified:' | wc -l)""

      - name: Format Success
        if: steps.format.outputs.NUM_CHANGED == 0
        run: echo "All matched files use Prettier code style!"

      - name: Format Error
        if: steps.format.outputs.NUM_CHANGED > 0
        run: echo "::set-failed ::Code style issues found in the above file(s). Forgot to run Prettier locally?"

  lint:
    runs-on: windows-2022
    needs: format

    strategy:
      matrix:
        node: [12, 14, 16]

    steps:
      - uses: actions/checkout@v2

      - name: Cache Node Modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install Dependencies
        run: npm i

      - name: Lint Code
        run: npm run lint:code

      - name: Lint Style
        run: npm run lint:style
