name: Spell Check | Lint | Format

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["master"]

jobs:
  spell:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm i -D cspell

      - name: Check Spelling
        run: npm run spell:check

  format:
    runs-on: windows-latest
    needs: spell

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm i -D prettier

      - name: Check Spelling
        run: npm run format:check

  lint:
    runs-on: windows-latest
    needs: format

    strategy:
      matrix:
        node: [12, 14, 16]

    steps:
      - uses: actions/checkout@v2

      - name: Cache Node Modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Test Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install Dependencies
        run: npm i

      - name: Lint Code
        run: npm run lint:code

      - name: Lint Style
        run: npm run lint:style
