name: TabMerger Testing

on:
  push:
    branches: ["master", "main"]
  pull_request:
    branches: ["master", "main"]

jobs:
  unit-testing:
    runs-on: windows-latest
    strategy:
      max-parallel: 5
      matrix:
        unit_test_type: ["test:app", "test:group", "test:tab", "test:background", "test:settings"]

    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Test using Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: Install Dependencies
        run: npm i

      - name: Run Tests
        run: npm run ${{ matrix.unit_test_type }}

      - name: Upload Coverage Report to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage/coverage-final.json

  mutation-testing:
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, 'SKIP MUTATION')"
    needs: unit-testing
    timeout-minutes: 420
    strategy:
      max-parallel: 9
      matrix:
        mutation_type:
          [
            "mutate:app-func",
            "mutate:app-help",
            "mutate:group",
            "mutate:tab-func",
            "mutate:tab-help",
            "mutate:background-func",
            "mutate:background-help",
            "mutate:settings-func",
            "mutate:settings-help",
          ]
    env:
      STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}

    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Test using Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: Install Dependencies
        run: npm i

      - name: Stryker Mutation Testing
        run: npm run ${{ matrix.mutation_type }}
